# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  job:  # This is the job name.
    parameters:
      PROJECT:
        type: string
    docker:
      - image: 'cimg/python:3.9.0'
    steps:
      - run: sudo apt-get update -qq
      - run: pip install --upgrade pip
      - run: pip install --upgrade virtualenv
      - checkout
      - run: ls
      - run: ./<<parameters.PROJECT>>/run.sh

workflows:
  all-tests:  # This is the workflow name.
    jobs:
      - job:  # This matches the job name above.
          matrix:
            parameters:
              PROJECT:
                - "abps"
                - "albert"
